insert into USER values
('kildong', password('ghdrlfehd'), '홍길동', '2008-30020', '국어교육', 2, 'kildong@phpschool.ac.kr'),
('lee', password('dlahdfyd'), '이몽룡', '2008-31001', '수학교육', 2, 'lee@phpschool.ac.kr'),
('sch', password('tjdcnsgid'), '성춘향', '2009-37002', '컴퓨터교육', 1, 'sch@phpschool.ac.kr'),
('kim', password('rlaghdeh'), '김홍도', '2009-37005', '컴퓨터교육', 1, 'kim@phpschool.ac.kr'),
('young', password('wkddudtlf'), '장영실', '2008-31010', '컴퓨터교육', 2, 'young@phpschool.ac.kr') ;